openapi: 3.0.3
info:
  title: WASAphoto API
  description: |
    This is the API for WASAphoto made by 1982048
  version: 0.0.1

tags: 
  - name: "login"
    description: Endpoint that manages the login
  - name: "search"
    description: Endopint that manages search user profile
  - name: "user"
    description: Endpoint that manages users
  - name: "stream"
    description: Endpoint that manages stream
  - name: "ban"
    description: Endpoint that manages banned users
  - name: "followers"
    description: Endpoint that manages followers
  - name: "photo"
    description: Endpoint that manages photos
  - name: "comments"
    description: Endpoint that manages comments
  - name: "likes"
    description: Endpoint that manages likes

paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user_login"
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/login_return" 
  
  /users:
    get:
      tags: ["search"]
      summary: Gets the profile of the user with a certain id
      description: A user can find another user's profile only if he's not banned by the latter. Multiple users might match partially the nickname being searched
      operationId: getUserProfile

      parameters: 
        - $ref: "#/components/parameters/query_id"

      responses:
        '200':
          $ref: "#/components/responses/user_found" 
        '401':
          $ref: "#/components/responses/unauthorized"
        '404':
          $ref: "#/components/responses/not_found"
        '500':
          $ref: "#/components/responses/internal_server_error"
          
      security:
        - bearerAuth: []   

  /users/{id}:
    parameters:
      - $ref: "#/components/parameters/identifier"
    get:
      tags: ["user"]
      summary: Retrieves all the info of a profile
      description: Allows the user to obtain a profile complete info (can't be banned by the profile owner)
      operationId: getProfile
      
      responses:
        '200':
          $ref: "#/components/responses/profile"
        '206':
          $ref: "#/components/responses/partial_content"
        '401':
          $ref: "#/components/responses/unauthorized"
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: "#/components/responses/not_found"
        '500':
          $ref: "#/components/responses/internal_server_error"
      security:
        - bearerAuth : []
    put: 
      tags: ["user"]
      summary: Set username
      description: |-
        Set a new username
      operationId: setMyUserName
      requestBody:
        description: User username
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/user_nickname"
        required: true
      responses:
        "204": { $ref: "#/components/responses/no_content" }
        "401": { $ref: "#/components/responses/unauthorized" }
        "403": { $ref: "#/components/responses/forbidden" }
        "404": { $ref: "#/components/responses/not_found" }
        "500": { $ref: "#/components/responses/internal_server_error" }
  
  /users/{id}/home:
    parameters:
      - $ref: "#/components/parameters/identifier"
    get:
      security:
      - bearerAuth : []
      tags: ["stream"]
      summary: Return stream
      description: |-
        Return a list of photos for the user stream.
      operationId: getMyStream
      responses:
        "200": { $ref: "#/components/responses/stream"}
        "401": { $ref: "#/components/responses/unauthorized" }
        "403": { $ref: "#/components/responses/forbidden" }
        "404": { $ref: "#/components/responses/not_found" }
        "500": { $ref: "#/components/responses/internal_server_error" }
 
  /users/{id}/banned_users/{banned_user_id}:
    parameters:
        - $ref: "#/components/parameters/banned_user_id"
        - $ref: '#/components/parameters/identifier'
    put:
      security:
      - bearerAuth : []
      tags: ["ban"]
      summary: Ban user
      description: |-
       Ban an user.
      operationId: banUser
      responses:
        "204": 
          description: User banned successfully.
          content:
            application/json:
              schema: 
                $ref: "#/components/responses/no_content"
        "401": { $ref: "#/components/responses/unauthorized" }
        "403": { $ref: "#/components/responses/forbidden" }
        "404": { $ref: "#/components/responses/not_found" }
        "500": { $ref: "#/components/responses/internal_server_error" }

    delete:
      security:
      - bearerAuth : []
      tags: ["ban"]
      summary: Unban user
      description: |-
        Unban an user.
      operationId: unbanUser

      responses:
        "204": { description: Ban deleted successfully. }
        "401": { $ref: "#/components/responses/unauthorized" }
        "403": { $ref: "#/components/responses/forbidden" }
        "404": { $ref: "#/components/responses/not_found" }
        "500": { $ref: "#/components/responses/internal_server_error" }
  
  /users/{id}/followers/{follower_id}:
    parameters:
      - $ref: "#/components/parameters/identifier"
      - $ref: "#/components/parameters/follower_id"
    put: 
      security:
      - bearerAuth : []
      tags: ["followers"]
      summary: Follow user
      description: |-
        Folow an user.
      operationId: followUser
      responses:
        "204": 
          description: User followed successfully.
          content:
            application/json:
              schema: 
                $ref: "#/components/responses/no_content"
        "401": { $ref: "#/components/responses/unauthorized" }
        "403": { $ref: "#/components/responses/forbidden" }
        "404": { $ref: "#/components/responses/not_found" }
        "500": { $ref: "#/components/responses/internal_server_error" }
  
    delete: 
      security:
      - bearerAuth : []
      tags: ["followers"]
      summary: Unfollow user
      description: |-
       Unfollow an user.
      operationId: unfollowUser
      responses:
        "204": { description: Follow deleted successfully. }
        "401": { $ref: "#/components/responses/unauthorized" }
        "403": { $ref: "#/components/responses/forbidden" }
        "404": { $ref: "#/components/responses/not_found" }
        "500": { $ref: "#/components/responses/internal_server_error" }
  
  
  /users/{id}/photos/{photo_id}:
    parameters:
      - $ref : "#/components/parameters/identifier"
      - $ref : "#/components/parameters/photo_id"
    get:
      tags: ["photo"]
      summary: Downloads a photo
      description: A user can access a photo if he/she's the owner or if he/she wasn't banned by the owner
      operationId: getPhoto
      
      responses:
        '200':
          $ref: "#/components/responses/photo"
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: "#/components/responses/not_found"
        '500':
          $ref: "#/components/responses/internal_server_error"
          
      security:
        - bearerAuth: [] 
    delete:
      security:
      - bearerAuth : []
      tags: ["photo"]
      operationId: deletePhoto
      summary: Remove photo
      description: |-
       Delete a photo.
      responses:
        "204": { description: Photo deleted successfully. }
        "401": { $ref: "#/components/responses/unauthorized" }
        "403": { $ref: "#/components/responses/forbidden" }
        "404": { $ref: "#/components/responses/not_found" }
        "500": { $ref: "#/components/responses/internal_server_error" }
  
  /users/{id}/photos:
    parameters:
      - $ref : "#/components/parameters/identifier"
    post: 
      security:
      - bearerAuth : []
      tags: ["photo"]
      summary: Upload photo
      description: |-
        Upload a photo.
      operationId: uploadPhoto 
      requestBody:
        description: photo
        required: true
        content:
          image/*:
            schema:
              description: Image schema.
              type: object
              properties:
                 file: 
                  description: file
                  type: string
                  format: binary
                  minLength: 0
                  maxLength: 9999   
      responses:
        "201":
          description: Photo uploaded successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/photo_uploaded"
        "401": { $ref: "#/components/responses/unauthorized" }
        "403": { $ref: "#/components/responses/forbidden" }
        "500": { $ref: "#/components/responses/internal_server_error" }
  /users/{id}/photos/{photo_id}/likes/{like_id}:
    parameters:
      - $ref: "#/components/parameters/identifier"
      - $ref : "#/components/parameters/photo_id"
      - $ref : "#/components/parameters/like_id"
    put: 
      security:
      - bearerAuth : []
      tags: ["likes"]
      operationId: likePhoto
      summary: Like photo
      description: |-
        Add a like to a specific photo.
      responses:
        "204":
          description: Like added successfully.
          content:
            application/json:
              schema: 
                $ref: "#/components/responses/no_content"
        "401": { $ref: "#/components/responses/unauthorized" }
        "403": { $ref: "#/components/responses/forbidden" }
        "404": { $ref: "#/components/responses/not_found" }
        "500": { $ref: "#/components/responses/internal_server_error" }
    delete: 
      security:
      - bearerAuth : []
      tags: ["likes"]
      operationId: unlikePhoto
      summary: Delete like
      description: |-
        Remove a like from a specific photo.
      responses:
        "204": { description: Like deleted successfully. }
        "401": { $ref: "#/components/responses/unauthorized" }
        "403": { $ref: "#/components/responses/forbidden" }
        "404": { $ref: "#/components/responses/not_found" }
        "500": { $ref: "#/components/responses/internal_server_error" }
  /users/{id}/photos/{photo_id}/comments:
    parameters: 
        - $ref: '#/components/parameters/identifier'
        - $ref: '#/components/parameters/photo_id'
        
    post:
      security:
      - bearerAuth : []
      tags: ["comments"]
      summary: Add comment
      operationId: commentPhoto
      description: |-
       Add a comment under a specific photo.
      requestBody:
        description: Comment 
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/comment"
        required: true
      responses:
        "201":
          description:  Comment added successfully.
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/comment_added"
        "401": { $ref: "#/components/responses/unauthorized" }
        "403": { $ref: "#/components/responses/forbidden" }
        "404": { $ref: "#/components/responses/not_found" }
        "500": { $ref: "#/components/responses/internal_server_error" }
  /users/{id}/photos/{photo_id}/comments/{comment_id}:
    parameters:
      - $ref: "#/components/parameters/identifier"
      - $ref: "#/components/parameters/photo_id"
      - $ref: "#/components/parameters/comment_id"
    delete:
     security:
     - bearerAuth : []
     tags: ["comments"]
     operationId: uncommentPhoto
     summary: Remove comment
     description: |-
       Deletete a comment under a specific photo.
     responses:
        "204": { description: Comment deleted successfully. }
        "401": { $ref: "#/components/responses/unauthorized" }
        "403": { $ref: "#/components/responses/forbidden" }
        "404": { $ref: "#/components/responses/not_found" }
        "500": { $ref: "#/components/responses/internal_server_error" }


components:
#securitySchemes
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

#Responses
  responses: 
    unauthorized:
      description: Access token is missing or invalid
    not_found:
      description: The request was not compliant with the documentation (eg. missing fields, etc).
    internal_server_error:
      description: The server encountered an internal error. Further info in server logs.
    no_content:
      description: Response associated to the 204 http status 
    partial_content:
      description: Response associated to the 206 http status 
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/complete_profile" 
    forbidden:
      description: Response associated to the 403 http status (Access denied )
    user_found:
      description: There's a match for the given identifier/nickname. User/users found successfully
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/users_list"         
    stream:
      description: Contains a list of photos from following users in a reversed chronological order
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/photos"          
    profile:
      description: All the info of a profile
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/complete_profile"
    photo:
      description: The binary data of a photo
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/raw_photo"
  
#Parameters
  parameters:
   
    identifier:
      name: id
      in: path
      description: A user's unique id
      required: true
      schema:
        description: String between 3-16 characters
        type: string
        pattern: '^.*?$'
        example: Francesco02
        minLength: 3
        maxLength: 16
        readOnly: true  

    photo_id:
      name: photo_id
      in: path
      description: A photo unique identifier
      required: true
      schema: 
        description: Int64 between 0-9999
        type: integer
        format: int64
        minimum: 0
        maximum: 9999
        example : 999
        readOnly: true
     
    comment_id:
      name: comment_id
      in: path
      description: A comment unique identifier
      required: true
      schema:
        $ref: "#/components/schemas/comment_identifier/properties/comment_id"
      example: 200
       
    follower_id:
      name: follower_id
      in: path
      description: A follower's unique identifier. It's exactly his *identifier*
      required: true
      schema: 
        $ref: "#/components/schemas/user_nickname/properties/nickname"
      example: "Sofia"
     
    like_id:
      name: like_id
      in: path
      description: A like unique identifier. It's exactly the *identifier* of the user that liked the photo
      required: true
      schema: 
        $ref: "#/components/schemas/user_nickname/properties/nickname"
      example: "AndreaC"
       
    banned_user_id:
      name: banned_user_id
      in: path
      description: A banned user unique identifier. It's exactly the *identifier* of the user
      required: true
      schema:
        $ref: "#/components/schemas/user_nickname/properties/nickname"
      example: "Killer"
      
    query_id:
      name: id
      in: query
      description: id of the user that is being searched
      schema:
        description: usual *identifier*
        type: string
        pattern: '^.*?$'
        minLength: 3
        maxLength: 16
        example: "Franco99"
      example: "Francesco02"
#Schemas
  schemas:

    user_nickname:
      description: It's a user's nickname
      type: object
      properties:
        nickname:
          description: Any string between 3-16 characters
          type: string
          minLength: 3
          maxLength: 16
          pattern: '^.*?$'
          example: "FrancescoErrico"
      example:
        nickname: "Francescoe02"
  
    complete_user:
      description: Contains both *unique identifier and nickname of a user
      type: object
      properties:
        user_id:
          $ref: "#/components/schemas/user_nickname/properties/nickname"
        nickname:
          $ref: "#/components/schemas/user_nickname/properties/nickname"
      example:
        user_id: "FrancescoErrico"
        nickname: "Francescoe02"

    comment_identifier:
      description: It's a comment *unique* id
      type: object
      properties:
        comment_id:
          description: Any number between 0-9999
          type: integer
          format: int64
          minimum: 0
          maximum: 9999
          readOnly: true
          example: 965
      example:
        comment_id: 965
        
    comment:
      description: A user's comment contains the text of the comment and the *identifier* of who commented
      type: object
      properties:
        user_id: 
          $ref: "#/components/schemas/user_nickname/properties/nickname"
        nickname: 
          $ref: "#/components/schemas/user_nickname/properties/nickname"
        comment:
          type: string
          minLength: 1
          maxLength: 30
          pattern: '^.*?$'
          example: It's Beautiful
          description: String value of the comment
        comment_id:
          $ref: "#/components/schemas/comment_identifier/properties/comment_id"
      example:
        user_id: "Sofia2002"
        nickname: "sofi"
        photo_id: 873
        comment: "Wow che foto spectacularesss"    
        comment_id: 16

    raw_photo:
      description: Image content
      type: object
      properties:
        photo_data:
          description: "Raw data of the photo"
          type: string
          minLength: 0
          maxLength: 100
          format: binary
          example: "010110010"
      example: 
        photo_data: "010110010"

    photo:
      description: Contains the essential info of a photo
      type: object
      properties:
        comments:
          description: Array of comments of a photo
          type: array
          minItems: 0
          maxItems: 9999
          items:
            $ref: "#/components/schemas/comment"
          example:
            - comments:
              - user_id: "Alessio"
                nickname: "Ale46"
                photo_id: 3821
                comment: "bella foto!"
                comment_id: 23
        likes:
          description:  Array of users that liked a photo
          type: array
          minItems: 0
          maxItems: 9999
          items:
            $ref: "#/components/schemas/complete_user"
          example: 
            -  user_id: "FrancescoSnorfia"
               nickname: "Franco33"
            -  user_id: "Enzo44"
               nickname: "kami"
        date:
          description: Date and time of upload.
          type: string
          format: date-time
          example: 2017-07-21T17:32:28Z
          readOnly: true
        photo_id:
          $ref: "#/components/schemas/comment_identifier/properties/comment_id"
        owner:
          $ref: "#/components/schemas/user_nickname/properties/nickname"
      example: 
        comments:
          - user_id: "Alessio"
            nickname: "Ale46"
            photo_id: 3821
            comment: "bella foto!"
            comment_id: 99
        likes:
          - user_id: "Alessio"
            nickname: "Ale46"
        date: 2017-07-21T17:32:28Z
        photo_id: 3821
        owner: "Mariucc"
     
    photos:
      description: Represents a list of photos
      type: object
      properties:
        photos_list:
          description: List of photos
          type: array
          minItems: 0
          maxItems: 10
          items:
            $ref: "#/components/schemas/photo"
          example:
            - comments:
                - user_id: "Donato"
                  nickname: "Dona99"
                  photo_id: 8321
                  comment: "wow, nice"
                  comment_id: 7
                - user_id: "Vittorio"
                  nickname: "Vittorio66"
                  photo_id: 8321
                  comment: "impossible!"
                  comment_id: 76
            - likes:
              - user_id: "Donato"
                nickname: "Dona"
              - user_id: "Vittorio"
                nickname: "Vittorio66"
              date: 2017-07-21T17:32:28Z
              photo_id: 8321
              owner: "Sofia2002"
              
            - comments:
                - user_id: "Sofia"
                  nickname: "Sofia2002"
                  photo_id: 7836
                  comment: "bellissimo"
                  comment_id: 44
                - user_id: "Enzo"
                  nickname: "kami"
                  photo_id: 7836
                  comment: "grande bro"
                  comment_id: 912
            - likes:
              - user_id: "Francesco"
                nickname: "Francesco02"
              - user_id: "Ernesto"
                nickname: "pistola33"
              - user_id: "Vittorio"
                nickname: "Vittorio66"
              date: 2022-11-22T13:10:14Z
              photo_id: 7836
              owner: "Francescoe02"
    
    users_list:
      description: List of users found
      type: object
      properties:
        users:
          description: Array of users with a partial match on the searched nickname
          type: array
          minItems: 0
          maxItems: 10
          items:
            $ref: "#/components/schemas/complete_user"
          example:
            - user_id: Wario21
              nickname: marietto21
            - user_id: Watermelon
              nickname: cocomeros
            - user_id: WaveBruh
              nickname: ondaBro
            - user_id: WantedMan66
              nickname: uomoRicercato

    complete_profile:
          description: Object containing all the profile info
          type: object
          properties:
          
            user_id:
              $ref: "#/components/schemas/user_nickname/properties/nickname"
              
            nickname:
              $ref: "#/components/schemas/user_nickname/properties/nickname"
              
            followers:
              description: Array of followers
              type: array
              minItems: 0
              maxItems: 99
              items:
                $ref: "#/components/schemas/complete_user"
              example:
                - user_id: "Wario21"
                  nickname: "warietto21"
                - user_id: "giulio"
                  nickname: "Milioo"

            following:
              description: Array of followed users
              type: array
              minItems: 0
              maxItems: 99
              items:
                $ref: "#/components/schemas/complete_user"
              example:
                - user_id: "giulio"
                  nickname: "Milioo"
                
            photos:
              description: Array of photos
              type: array
              minItems: 0
              maxItems: 10
              items:
                $ref: "#/components/schemas/photo"
              example:
                - comments:
                  - user_id: "sfera"
                    nickname: "noNo"
                    comment: "bella li"
                    comment_id: 104
                  - user_id: "tiziano"
                    nickname: "ferroZ68"
                    comment: "spaccaaa"
                    comment_id: 99
                - likes:
                  - user_id: "sfera"
                    nickname: "noNo"
                  - user_id: "tiziano"
                    nickname: "ferroZ68"
                  - user_id: "raffaello"
                    nickname: "raffaello99"
                    
                  date: 2022-11-22T13:10:14Z
                  photo_id: 7836
                  owner: "PulpFiction"
         
    user_login:
      description: Identifier sent by user during the login
      type: object
      properties:
        identifier:
          $ref: "#/components/schemas/user_nickname/properties/nickname"
         
    login_return:
      description: Identifier returned after the login
      type: object
      properties:
        identifier:
          $ref: "#/components/schemas/user_nickname/properties/nickname"
    comment_added:
      description: Comment has been added successfully. Returns the comment *unique* identifier
      type: object
      properties:
        identifier:
             $ref: "#/components/schemas/comment_identifier"          
    photo_uploaded:
      description: photo has been uploaded successfully. Returns the *unique* id of the posted photo
      type: object
      properties:
        identifier:
            $ref: "#/components/schemas/photo"
